# Phundament 4 - Instant demo stack

cli:
  command: yii cli
  image: phundament/app:latest
  links:
    - 'mariadb:DB'
  volumes:
    - /app
    - ./src/commands/CliController.php:/app/src/commands/CliController.php

mariadb:
  image: 'tutum/mariadb:10.1'
  environment:
    MARIADB_PASS: secretadmin