# Phundament 4 - Instant demo stack

php:
  command: "sh -c 'sh /app/src/setup.sh && php-fpm'"
  image: phundament/app:4.0.0-rc11
  env_file: docker-compose.env
  links:
    - 'mariadb:DB'
  volumes:
    - /app

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'
  volumes_from:
    - php
  ports:
    - 20080:80

mariadb:
  image: 'tutum/mariadb:10.1'
  environment:
    MARIADB_PASS: secretadmin